<?php
/**
 * @file
 * Code for the Farm Mushroom feature.
 */

include_once 'farm_mushroom.features.inc';

/**
 * Implements hook_farm_ui_entities().
 */
function farm_mushroom_farm_ui_entities() {
  return array(
    'farm_asset' => array(
      'substrate' => array(
        'label' => t('Mushroom Substrate'),
        'label_plural' => t('Mushroom Substrates'),
        'view' => 'farm_substrates',
      ),
    ),
    'taxonomy_term' => array(
      'farm_mushroom_species' => array(
        'label' => t('Mushroom Species'),
        'label_plural' => t('Mushroom Species'),
        'view' => 'farm_mushroom_species',
        'farm_asset' => 'substrate',
        'asset_view_arg' => 2,
      ),
      'farm_substrate_types' => array(
        'label' => t('Substrate Type'),
        'label_plural' => t('Substrate Types'),
        'view' => 'farm_substrate_types',
        'farm_asset' => 'substrate',
        'asset_view_arg' => 3,
      ),
    ),
  );
}

/**
 * Implements hook_farm_log_categories().
 */
function farm_mushroom_farm_log_categories() {

  // Provide an "Mushrooms" log category.
  return array('Mushrooms');
}

/**
 * Implements hook_feeds_importer_default_alter().
 */
function farm_mushroom_feeds_importer_default_alter(&$importers) {

  // Add extra field mappings to mushroom substrates.
  $name = 'farm_asset_substrate';
  if (!empty($importers[$name])) {
    $mappings = array(
      array(
        'source' => 'Species',
        'target' => 'field_farm_mushroom_species',
        'term_search' => '0',
        'autocreate' => 1,
        'language' => 'und',
      ),
      array(
        'source' => 'Substrate',
        'target' => 'field_farm_substrate_type',
        'term_search' => '0',
        'autocreate' => 1,
        'language' => 'und',
      ),
    );
    $importer_mappings =& $importers[$name]->config['processor']['config']['mappings'];
    $importer_mappings = array_merge($importer_mappings, $mappings);
  }
}

/**
 * Implements hook_feeds_tamper_default_alter().
 */
function farm_mushroom_feeds_tamper_default_alter(&$feeds_tampers) {

  // If farm_import is not installed, bail.
  if (!module_exists('farm_import')) {
    return;
  }

  // Make species required.
  $feeds_tamper = farm_import_feeds_tamper_plugin('farm_asset', 'substrate', 'Species', 'required');
  $feeds_tampers[$feeds_tamper->id] = $feeds_tamper;

  // Make substrate required.
  $feeds_tamper = farm_import_feeds_tamper_plugin('farm_asset', 'substrate', 'Substrate', 'required');
  $feeds_tampers[$feeds_tamper->id] = $feeds_tamper;
}
