<?php
/**
 * @file
 * Code for the Farm Mushroom feature.
 */

include_once 'farm_mushroom.features.inc';

/**
 * Implements hook_farm_access_perms().
 */
function farm_mushroom_farm_access_perms($role) {

  // Assemble a list of entity types provided by this module.
  $types = array(
    'farm_asset' => array(
      'substrate',
    ),
    'taxonomy' => array(
      'farm_mushroom_species',
      'farm_substrate_types',
    ),
  );

  // Grant different CRUD permissions based on the role.
  $perms = array();
  switch ($role) {

    // Farm Manager and Worker
    case 'Farm Manager':
    case 'Farm Worker':
      $perms = farm_access_entity_perms($types);
      break;

    // Farm Viewer
    case 'Farm Viewer':
      $perms = farm_access_entity_perms($types, array('view'));
      break;
  }

  return $perms;
}

/**
 * Implements hook_farm_admin_actions().
 */
function farm_mushroom_farm_admin_actions() {

  // Define actions.
  $actions = array(
    'mushroom_species' => array(
      'title' => t('Add a mushroom species'),
      'href' => 'admin/structure/taxonomy/farm_mushroom_species/add',
      'paths' => array(
        'farm/substrates',
        'farm/substrates/mushroom-species',
      ),
    ),
    'substrate' => array(
      'title' => t('Add a substrate'),
      'href' => 'farm/asset/add/substrate',
      'views' => array(
        'farm_substrates',
      ),
    ),
    'substrate_types' => array(
      'title' => t('Add a substrate type'),
      'href' => 'admin/structure/taxonomy/farm_substrate_types/add',
      'paths' => array(
        'farm/substrates',
        'farm/substrates/types',
      ),
    ),
  );
  return $actions;
}

/**
 * Implements hook_farm_asset_breadcrumb().
 */
function farm_mushroom_farm_asset_breadcrumb($farm_asset) {

  // If the asset is a substrate, add a link to the substrates list.
  $breadcrumb = array();
  if ($farm_asset->type == 'substrate') {
    $breadcrumb[] = l(t('Mushroom Substrates'), 'farm/substrates');
  }
  return $breadcrumb;
}

/**
 * Implements hook_farm_taxonomy_breadcrumb().
 */
function farm_mushroom_farm_taxonomy_breadcrumb($term) {
  $breadcrumb = array();

  // Switch through available vocabularies.
  switch ($term->vocabulary_machine_name) {

    // If the term is in farm_mushroom_species...
    case 'farm_mushroom_species':
      $breadcrumb[] = l(t('Mushroom Substrates'), 'farm/substrates');
      $breadcrumb[] = l(t('Mushroom Species'), 'farm/substrates/mushroom-species');
      break;

    // If the term is in farm_substrate_types...
    case 'farm_substrate_types':
      $breadcrumb[] = l(t('Mushroom Substrates'), 'farm/substrates');
      $breadcrumb[] = l(t('Substrate Types'), 'farm/substrates/types');
      break;

  }

  return $breadcrumb;
}

/**
 * Implements hook_farm_asset_view_views().
 */
function farm_mushroom_farm_asset_view_views($farm_asset) {

  // If the entity is not a substrate, bail.
  if ($farm_asset->type != 'substrate') {
    return array();
  }

  // Return a list of Views to include on Substrates.
  return array(
    'farm_log_activity',
    'farm_log_observation',
    'farm_log_movement',
  );
}

/**
 * Implements hook_farm_taxonomy_term_view_views().
 */
function farm_mushroom_farm_taxonomy_term_view_views($term) {

  // Start a list of View names.
  $views = array();

  // Switch logic depending on the vocabulary.
  switch ($term->vocabulary_machine_name) {

    // Farm areas:
    case 'farm_areas':
      $views[] = array(
        'name' => 'farm_substrates',
        'arg' => 1,
        'weight' => 0,
      );
      break;

    // Farm substrate types.
    case 'farm_substrate_types':
      $views[] = array(
        'name' => 'farm_substrates',
        'arg' => 2,
      );
      break;

    // Farm mushroom species.
    case 'farm_mushroom_species':
      $views[] = array(
        'name' => 'farm_substrates',
        'arg' => 3,
      );
      break;
  }

  return $views;
}

/**
 * Implements hook_farm_area_links().
 */
function farm_mushroom_farm_area_links($id) {
  return array(
    array(
      'title' => t('Mushroom Substrates'),
      'href' => 'taxonomy/term/' . $id,
      'options' => array(
        'fragment' => 'Substrates',
      ),
    ),
  );
}

/**
 * Implements hook_page_build().
 */
function farm_mushroom_page_build(&$page) {

  // If this is the mushrooms page, display the substrate asset map.
  $current_path = current_path();
  $map_paths = array(
    'farm/substrates',
    'farm/substrates/list',
  );
  if (in_array($current_path, $map_paths)) {

    // Load the assets map.
    $map = \Drupal\openlayers\Openlayers::load('Map', 'farm_assets_substrate');

    // Build the map and add it to the page content.
    $page['content']['farm_assets_substrate'] = $map->build();

    // Set the weight to -100 so that it appears on top.
    $page['content']['farm_assets_substrate']['#weight'] = -100;

    // Set the content region #sorted flag to FALSE so that it resorts.
    $page['content']['#sorted'] = FALSE;
  }
}
